### ISSUE TITLE
'Domain supply' Error message at 'Running the image' stage

### ISSUE THREAD

**Issue by alvincyram** [whyhow-ai/knowledge-graph-studio#3]
## 
I want to test your KG studio on Window Docker desktop. 
When I run 'docker run -it --rm -p 1234:8000 kg_engine:v1', 
I get the following Error message - 'ValueError: domain must be supplied.'. 

I would appreciate any advice on how to resolve this error.

## What I did:

kg-enginge> docker run -it --rm -p 1234:8000 kg_engine:v1

## Screenshots
INFO:     Started server process [17]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/usr/local/lib/python3.10/site-packages/whyhow_api/main.py", line 53, in lifespan
    jwks_url = settings.api.auth0.jwks_url
  File "/usr/local/lib/python3.10/site-packages/whyhow_api/config.py", line 110, in jwks_url
    raise ValueError("domain must be supplied.")
ValueError: domain must be supplied.

ERROR:    Application startup failed. Exiting.

**Comment by recchris** [comment]
Hey Alvin, the `.env.sample` may have been missing. Copy that to `.env`, add values and you should be good to go.

**Comment by alvincyram** [comment]
Thanks for quick response. I'll try it!

**Comment by recchris** [comment]
FYI, we just added the following:
- Removed default auth0 logic (not needed for running the knowledge graph studio backend, so this is no longer a dependency for getting started)
- Added scripts for MongoDB Atlas setup, including a cli script for creating all the collections and a script for creating your user (in `src/whyhow_api/cli`)
- Added more detailed instructions to `README` for getting started. We will be continually improving the documentation.

Hopefully that clears it up. Thx!

**Comment by alvincyram** [comment]
Hi!
Many THANKS for your kind support. 
I'll try it again ASAP.

**Comment by recchris** [comment]
Hey @alvincyram, are we good to close this issue? Thx!

**Comment by alvincyram** [comment]
OK. 
Unfortunately, I haven't tested it enough yet, but I think I'll close this issue.
Thank you very much for your quick and friendly guidance.
